### ISSUE TITLE
Restart server if gobpie.json is changed

### ISSUE THREAD

**Issue by karoliineh** [goblint/GobPie#23]
As the Goblint server can only reparse files and not analyse a new set of files when the server is already running, the server must be shut down and started again if a new set of files is passed. Right now one must always close and reopen VSCode to start an analysis on different sets of files in the project, which is quite inconvenient.

**Comment by sim642** [comment]
With #24 the `files` field would move from `gobpie.json` to `goblint.json`, but the overall point still remains. It's just that if `goblint.json` is changed, the server should also be restarted.

**Comment by michael-schwarz** [comment]
In principle there is also nothing stopping us from adding a `reset`
command to the server that resets all internal state.
The question would be if there are any advantages to doing so over killing
it?

**Comment by sim642** [comment]
Such command was already added in https://github.com/goblint/analyzer/pull/817 since our loading of configs is really a cumulative merging of configs. So in order to be able to get predictable behavior on config file changes, it was necessary to also reset and re-merge instead.

As usual with the server, the advantage still is that it avoids having to marshal and unmarshal all the incremental data just to add a new file to the analyzed project, etc.

**Comment by michael-schwarz** [comment]
I sent the email with this comment on `Thu, Mar 10, 10:02 PM`, very strange that it appeared here yesterday.
