### ISSUE TITLE
Show goblint's stdout/stderr in the GoblintAnalyzer output view

### ISSUE THREAD

**Issue by vesalvojdani** [goblint/GobPie#8]
There are still some tricky things that can happen if the goblint path is not properly set up. If goblint does not find its include files it will warn about this, but will still exit with status 0. Checking assertions does not work without our own `assert.h` hack. So it would be good to have a bit more diagnostic output:

- [x] Save all the debug info that Goblint dumps into stdout/stderr and show this in GoblintAnalyzer output view.
- [ ] Check if the output contains certain phrases and display these as visible warnings (and try it with the phrase `Warning, cannot find goblint's custom include files.`)
- [x] Output the command goblint was executed with somewhere. Does that analysis started allow some extra information; otherwise, this could also just be dumped into the GoblintAnalzyer output.
- [ ] Bump the version to 0.0.2 or something :)

**Comment by sim642** [comment]
The key part of this issue was fixed, so should it be closed? The issue was linked after merging, so that didn't happen automatically.

Or is there real need for hardcoding some Goblint warnings to check into GobPie?

**Comment by karoliineh** [comment]
I didn't close it because as I understood previously, the "just redirect everything Goblint dumps into the output", although being better than seeing nothing,  is not the best approach. 

The "Check if the output contains certain phrases and display these as visible warnings (and try it with the phrase Warning, cannot find Goblint's custom include files.)" task has not been implemented. Should this (some kind of processing of Goblint's dump) happen in GobPie or are we going to clean the Goblint's dump so that the "just pump everything Goblint dumps into the output" becomes a good approach?

I didn't bump the version though (last subtask), but I guess all the licence, extension's name etc. settings part should be dealt with at some point anyway. Maybe I should create a separate issue for that?

**Comment by sim642** [comment]
I would be fine with just closing this issue and not hardcoding any special behavior for certain Goblint output because it could easily go out of sync with Goblint itself.

Also versioning (releases) etc is a separate thing that we don't care about too much right now, given that even Goblint doesn't have an up-to-date release yet...
